# Generated by Django 3.2.14 on 2022-07-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('depth', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('buddy', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
